<?php
/**
 * The main file of the Schema Extensions for Yoast SEO by WP Munich plugin
 *
 * @package wpmschema
 * @version 1.1.0
 *
 * Plugin Name: Schema Extensions for Yoast SEO by WP Munich
 * Plugin URI: 
 * Description: Extend the Schema.org markup generated by Yoast SEO in small, but meaningful ways.
 * Author: WP Munich
 * Author URI: https://www.wp-munich.com
 * Version: 1.1.0
 * Text Domain: wpmschema
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

if ( ! defined( 'WPM_SCHEMA_SLUG' ) ) {
	define( 'WPM_SCHEMA_SLUG', 'wpm-schema' );
}

if ( ! defined( 'WPM_SCHEMA_VERSION' ) ) {
	define( 'WPM_SCHEMA_VERSION', '1.1.0' );
}

if ( ! defined( 'WPM_SCHEMA_URL' ) ) {
	define( 'WPM_SCHEMA_URL', plugin_dir_url( __FILE__ ) );
}

if ( ! defined( 'WPM_SCHEMA_PATH' ) ) {
	define( 'WPM_SCHEMA_PATH', plugin_dir_path( __FILE__ ) );
}

// Load the autoloader.
require WPM_SCHEMA_PATH . 'vendor/autoload.php';

// Load the `wp_wpmschema()` entry point function.
require WPM_SCHEMA_PATH . 'inc/functions.php';

if ( wp_get_environment_type() === 'development' ) {
	require WPM_SCHEMA_PATH . 'inc/test.php';
}

// Initialize the plugin.
call_user_func( 'WpMunich\wpmschema\wp_wpmschema' );
